[context.production.environment]
  PIXLET_BINARY = "pixlet-new"
  PIXLET_BINARY_PATH = "./functions/axilla"
  LD_LIBRARY_PATH = "./functions/axilla"

[context.branch-deploy.environment]
  PIXLET_BINARY = "pixlet-aws"
  PIXLET_BINARY_PATH = "./functions/axilla"
  LD_LIBRARY_PATH = "./functions/axilla"

[context.deploy-preview.environment]
  PIXLET_BINARY = "pixlet-aws"
  PIXLET_BINARY_PATH = "./functions/axilla"
  LD_LIBRARY_PATH = "./functions/axilla"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/axilla"
  status = 200

[functions]
  directory = "functions"
